# .github/workflows/deploy.yml
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # Publica quando houver push na branch main
  workflow_dispatch:     # Permite execução manual

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload dos arquivos do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # Usa o index.html que está na raiz do projeto

      - name: Fazer deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
